version: '3.7'

services:
  server:
    build: .
    ports:
      - "3000:3000"
    container_name: nest-server
    restart: always
    working_dir: /app
    environment:
      mongoDB: 
      dbName: 
      JWT_SECRET: 
  mongodb:
    image: mongo
    restart: always