version: '3.7'

services:
  server:
    build: .
    ports:
      - "3000:3000"
    container_name: nest-server
    restart: always
    working_dir: /app
  mongodb:
    image: mongo
    restart: always